# Generated by Django 5.0.5 on 2024-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_answermodel_owner_alter_commentmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='owner',
            field=models.IntegerField(default='Unknown', max_length=30),
        ),
    ]
