# Generated by Django 5.0.5 on 2024-05-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_questionmodel_question_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoiceModel',
            new_name='AnswerModel',
        ),
        migrations.RenameField(
            model_name='answermodel',
            old_name='choice_text',
            new_name='answer_text',
        ),
    ]
