# Generated by Django 5.0.5 on 2024-10-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_commentmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='owner',
        ),
    ]
