# Generated by Django 5.0.5 on 2024-10-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_commentmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created_by',
            field=models.TextField(default='Unknown', max_length=30),
        ),
    ]
