# Generated by Django 5.0.5 on 2024-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_choicemodel_answermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question_type',
            field=models.CharField(choices=[('Single choice', 'Single choice'), ('Multiple choices', 'Multiple choices'), ('Text', 'Open answer')], max_length=16),
        ),
    ]
