# Generated by Django 5.0.5 on 2024-10-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_commentmodel_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='owner',
            new_name='created_by',
        ),
    ]
