# Generated by Django 5.0.5 on 2024-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_questionmodel_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question_type',
            field=models.CharField(choices=[('Single choice', 'Single choice'), ('Multiple choices', 'Multiple choices'), ('Text', 'Text')], max_length=16),
        ),
    ]
