# Generated by Django 5.0.5 on 2024-10-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_owner_answermodel_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='created_by',
            new_name='owner',
        ),
    ]
