# Generated by Django 5.0.5 on 2024-07-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_questionmodel_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
