# Generated by Django 5.0.5 on 2024-10-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_created_by_answermodel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='anonymous_user_id',
            field=models.CharField(default='Reg'),
        ),
    ]
