# Generated by Django 5.0.5 on 2024-05-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='email',
            field=models.EmailField(error_messages={'blank': 'This field is required.', 'unique': 'A user with that email already exists.'}, max_length=150, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
