# Generated by Django 5.0.5 on 2024-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='auth_provider',
            field=models.CharField(default='App auth', max_length=150),
        ),
    ]
