# Generated by Django 5.0.5 on 2024-10-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountmodel_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
